### ISSUE TITLE
Beef up organization profile

### ISSUE THREAD

**Issue by dandv** [meteor-useraccounts/wiki#1]
See https://github.com/MeteorPackaging/ :)

**Comment by splendido** [comment]
Hey @dandv,
nice to see you here!

what do you mean?
Should I invite more people to the organization?
...actually it's four of us, but the other three are still marked as 'private'

In any case I agree `useraccounts` should be feeded more :-)
are you willing to somehow participate? ;-)

In case you're trying these packages out, let us know what you think!
It would be great to have a feedback from you, seriously!

@kevohagan, @queso, @softwarerero ping!

**Comment by splendido** [comment]
...perhaps you're just referring to the landing page?

**Comment by dandv** [comment]
Yes, referring to https://github.com/meteor-useraccounts

**Comment by splendido** [comment]
...something was added, but the logo will be a difficult one ;-)
Tnx!

**Comment by splendido** [comment]
Hey @dandv, the [logo is coming soon](https://github.com/meteor-useraccounts/core/issues/174#issuecomment-75163034)!

**Comment by dandv** [comment]
Neat!
